- name: demo on play level variables
  hosts: localhost
  connection: local
  vars:
    name: "noor"
    son: "Mahaboob subhani"
  tasks:
  - name: demo on task level variables
    vars:
      name: "shanu"
    debug:
      msg: " Hi, I am Shaik {{ name }} son of {{ son }}" 
