- name: demo on play level variables
  hosts: local
  connection: local
  vars:
    name: "noor"
    son: "Mahaboob subhani"
  tasks:
  - debug:
      msg: " Hi, I am Shaik {{ name }} son of {{ son }}" 
