- name: demo on promt
  hosts: localhost
  connection: local
  vars_prompt:
    - name: username
      promt: "Please enter the username"
      private: false
  vars_prompt:
    - name: password
      promt: "Please enter the password"
      private: true
  tasks:
  - name: demo
    debug:
      msg: "username is {{ username }} and password is {{ password }}"